spring.application.name=FinanceTracker

# Database Config
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false